backend:
  name: git-gateway
  branch: master

media_folder: "static/staticAssets/uploads"
public_folder: "/staticAssets/uploads"

collections:
  - name: 'Blog'
    label: 'Blog'
    folder: 'content/articles'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Publish Date", name: "publishDate", widget: "datetime"}
      - {label: "Enabled", name: "enabled", widget: "boolean", default: true}
      - {label: "Featured Post", name: "featured", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}
